name: XSS_GG

on:
  push:
    branches:
      - main

jobs:
  exploit-job:
    name: Exploit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install playwright typer requests pytest

      - name: Install Playwright browsers
        run: |
          npx playwright install

      - name: Run exploit
        run: |
          python xssgg.py exploit

      - name: Install pytest
        run: |
          python -m pip install pytest

      - name: Run tests
        run: |
          python -m pytest test_xssgg.py
